version: '3.8'
services:
  backend:
    build:
      context: '.'
      dockerfile: Dockerfile
    image: 'biseo/backend-prod'
    container_name: 'biseo-server-prod'
    expose:
      - '3000'
    ports:
      - '3000:3000'
    # NOTE: `env_file` overwrites `environment`
    env_file: '.env'
    environment:
      PORT: 3000
      DB_HOST: 'database'
      REDIS_HOST: 'redis'
      REDIS_PORT: 6379
    networks:
      biseo:
        aliases:
          - backend
    depends_on:
      - database
      - redis
  database:
    image: 'mongo:4.4'
    container_name: 'biseo-database'
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: 'biseo'
    volumes:
      - 'database-volume:/data/db'
    networks:
      biseo:
        aliases:
          - database
  redis:
    image: 'redis:6.2-alpine'
    container_name: 'biseo-redis'
    ports:
      - '6379:6379'
    networks:
      biseo:
        aliases:
          - redis

volumes:
  database-volume:

networks:
  biseo:
